// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using diegomoreno.Brq.Repository.Contexts.Entity;

#nullable disable

namespace diegomoreno.Brq.Repository.Migrations
{
    [DbContext(typeof(TrucksDbContext))]
    [Migration("20220314081152_DiegoMorenoAjustes")]
    partial class DiegoMorenoAjustes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.1.22076.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("diegomoreno.Brq.domain.Entities.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Series", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6cb23935-2cdc-488c-96bf-61fb8f90ea7d"),
                            Name = "FH"
                        },
                        new
                        {
                            Id = new Guid("2a0a4549-c1c2-472a-8639-1365446ac22f"),
                            Name = "FM"
                        });
                });

            modelBuilder.Entity("diegomoreno.Brq.domain.Entities.Truck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FabricationYear")
                        .HasColumnType("int");

                    b.Property<Guid>("IdSeries")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SerieYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSeries");

                    b.ToTable("Trucks", (string)null);
                });

            modelBuilder.Entity("diegomoreno.Brq.domain.Entities.Truck", b =>
                {
                    b.HasOne("diegomoreno.Brq.domain.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("IdSeries")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
